
@url_dev = http://localhost:3056/v1/api

### signup

POST {{url_dev}}/shop/signup
Content-Type: application/json
x-api-key: 435fa7fecd59a1cd61cfaa669ab53301065ba8160bb09bbbf827950049ab279b61b1ed7b3630ccd7f3c82a2b3635cc71fc3c0c669f563a4522b3c3effc5ffc11

{
    "name": "ShopVP",
    "email": "shopvp09@gmail.com",
    "password": "abcd123"
}
